import { GameCrop } from '@/src/types/game';

export const GAME_CROPS: GameCrop[] = [
  {
    id: 'rice',
    name: 'Paddy Rice',
    nameBn: 'আমন/বোরো ধান',
    category: 'Cereal Grain',
    waterDemand: 'HIGH',
    droughtTolerance: 'LOW',
    heatTolerance: 'HIGH',
    soilCompatibility: 'HIGH',
    soilBenefit: 'LOW',
    nitrogenFixing: false,
    growthDays: 120,
    seasonSuitability: ['Monsoon', 'Summer'],
    baseYieldKg: 4200,
    marketPricePerKg: 0.42,
    seedCost: 40,
    description: 'Staple grain that feeds half the planet. Requires heavy water flooding or monsoon rainfall.',
    agronomicTip: 'Avoid planting in dry or water-scarce periods. If water is limited, pair with Alternate Wetting & Drying (AWD).'
  },
  {
    id: 'maize',
    name: 'Field Maize',
    nameBn: 'ভুট্টা',
    category: 'Cereal / Fodder',
    waterDemand: 'MEDIUM',
    droughtTolerance: 'MEDIUM',
    heatTolerance: 'HIGH',
    soilCompatibility: 'HIGH',
    soilBenefit: 'MEDIUM',
    nitrogenFixing: false,
    growthDays: 100,
    seasonSuitability: ['Summer', 'Spring'],
    baseYieldKg: 6800,
    marketPricePerKg: 0.28,
    seedCost: 35,
    description: 'High-energy C4 crop with robust root architecture. Highly responsive to balanced nutrition.',
    agronomicTip: 'Deep rooting helps extract subsoil moisture, but susceptible to heat stress during silking.'
  },
  {
    id: 'lentils',
    name: 'Lentils (Masoor)',
    nameBn: 'মসুর ডাল',
    category: 'Pulse / Legume',
    waterDemand: 'LOW',
    droughtTolerance: 'HIGH',
    heatTolerance: 'MEDIUM',
    soilCompatibility: 'HIGH',
    soilBenefit: 'HIGH',
    nitrogenFixing: true,
    growthDays: 85,
    seasonSuitability: ['Winter', 'Spring'],
    baseYieldKg: 1400,
    marketPricePerKg: 1.10,
    seedCost: 30,
    description: 'Hardy drought-resilient pulse. Rhizobium root nodules capture atmospheric nitrogen and enrich soil.',
    agronomicTip: 'Conserves precious groundwater while replenishing soil fertility for following crops.'
  },
  {
    id: 'soybean',
    name: 'Soybean',
    nameBn: 'সয়াবিন',
    category: 'Oilseed Legume',
    waterDemand: 'MEDIUM',
    droughtTolerance: 'MEDIUM',
    heatTolerance: 'HIGH',
    soilCompatibility: 'HIGH',
    soilBenefit: 'HIGH',
    nitrogenFixing: true,
    growthDays: 105,
    seasonSuitability: ['Summer', 'Monsoon'],
    baseYieldKg: 2800,
    marketPricePerKg: 0.55,
    seedCost: 45,
    description: 'High protein and oil content. Powerful biological nitrogen factory that revitalizes exhausted soils.',
    agronomicTip: 'Ideal break-crop after cereal monocultures like continuous rice or wheat.'
  },
  {
    id: 'wheat',
    name: 'Winter Wheat',
    nameBn: 'গম',
    category: 'Cereal Grain',
    waterDemand: 'MEDIUM',
    droughtTolerance: 'MEDIUM',
    heatTolerance: 'LOW',
    soilCompatibility: 'HIGH',
    soilBenefit: 'MEDIUM',
    nitrogenFixing: false,
    growthDays: 110,
    seasonSuitability: ['Winter', 'Spring'],
    baseYieldKg: 3600,
    marketPricePerKg: 0.38,
    seedCost: 35,
    description: 'Cool-season cereal essential for global bread production. Requires moderate soil moisture.',
    agronomicTip: 'Terminal heat stress above 32°C during grain filling can reduce test weight significantly.'
  },
  {
    id: 'chickpea',
    name: 'Chickpea (Gram)',
    nameBn: 'ছোলা',
    category: 'Pulse / Legume',
    waterDemand: 'LOW',
    droughtTolerance: 'HIGH',
    heatTolerance: 'HIGH',
    soilCompatibility: 'HIGH',
    soilBenefit: 'HIGH',
    nitrogenFixing: true,
    growthDays: 95,
    seasonSuitability: ['Winter', 'Spring'],
    baseYieldKg: 1600,
    marketPricePerKg: 0.95,
    seedCost: 32,
    description: 'Extremely water-efficient deep-taproot legume. Excellent for post-monsoon residual moisture.',
    agronomicTip: 'Requires no synthetic nitrogen fertilizers; fixes up to 70 kg of natural nitrogen per hectare.'
  },
  {
    id: 'tomato',
    name: 'Field Tomato',
    nameBn: 'টমেটো',
    category: 'Solanaceous Vegetable',
    waterDemand: 'HIGH',
    droughtTolerance: 'LOW',
    heatTolerance: 'MEDIUM',
    soilCompatibility: 'MEDIUM',
    soilBenefit: 'LOW',
    nitrogenFixing: false,
    growthDays: 75,
    seasonSuitability: ['Winter', 'Spring'],
    baseYieldKg: 18000,
    marketPricePerKg: 0.60,
    seedCost: 50,
    description: 'High-value cash crop requiring steady, drip-calibrated irrigation and well-drained loam.',
    agronomicTip: 'Sensitive to blossom end rot if soil moisture fluctuates erratically.'
  },
  {
    id: 'potato',
    name: 'Potato',
    nameBn: 'আলু',
    category: 'Tuber',
    waterDemand: 'MEDIUM',
    droughtTolerance: 'LOW',
    heatTolerance: 'LOW',
    soilCompatibility: 'HIGH',
    soilBenefit: 'MEDIUM',
    nitrogenFixing: false,
    growthDays: 90,
    seasonSuitability: ['Winter'],
    baseYieldKg: 22000,
    marketPricePerKg: 0.25,
    seedCost: 60,
    description: 'High calorie-yielding tuber. Prefers cool nights and friable, aerated, uncompacted soil.',
    agronomicTip: 'Excessive heat prevents tuber bulking. Keep soil evenly moist.'
  },
  {
    id: 'covercrop',
    name: 'Green Manure / Clover',
    nameBn: 'সবুজ সার / ক্লোভার',
    category: 'Soil Restorative',
    waterDemand: 'LOW',
    droughtTolerance: 'HIGH',
    heatTolerance: 'HIGH',
    soilCompatibility: 'HIGH',
    soilBenefit: 'HIGH',
    nitrogenFixing: true,
    growthDays: 50,
    seasonSuitability: ['Spring', 'Summer', 'Monsoon', 'Winter'],
    baseYieldKg: 800,
    marketPricePerKg: 0.40,
    seedCost: 20,
    description: 'Soil healing crop planted to suppress weeds, prevent erosion, and boost active microbial organic matter.',
    agronomicTip: 'Best choice after heavily depleted soil to restore vital carbon structure.'
  }
];
