import { Crop } from '@/src/types';

export const CROPS: Record<string, Crop> = {
  rice: {
    id: 'rice',
    name: 'Rice (Paddy)',
    localNames: { bn: 'ধান (Paddy)', en: 'Rice' },
    category: 'Cereal',
    waterDemand: 'High',
    waterDemandMmPerSeason: 1200,
    soilImpact: 'Depleting',
    soilHealthDelta: -6,
    nitrogenFixing: false,
    droughtTolerance: 'Low',
    heatTolerance: 'Moderate',
    growingDurationDays: 120,
    idealSoils: ['Clay', 'Silty', 'Loamy'],
    compatibleAfter: ['soybean', 'lentil', 'chickpea', 'cover_crop', 'mustard'],
    incompatibleAfter: ['rice'], // Continuous rice causes nematode and soil anaerobic degradation
    climateRiskScore: 68,
    typicalYieldTonPerHectare: 4.8,
    economicValue: 'High',
    carbonSequestration: 'Low',
    description: 'High caloric staple with intensive seasonal water requirements. Benefits strongly from legume rotation to restore microbial health.',
    icon: '🌾',
  },
  wheat: {
    id: 'wheat',
    name: 'Winter / Spring Wheat',
    localNames: { bn: 'গম (Wheat)', en: 'Wheat' },
    category: 'Cereal',
    waterDemand: 'Medium',
    waterDemandMmPerSeason: 450,
    soilImpact: 'Neutral',
    soilHealthDelta: -1,
    nitrogenFixing: false,
    droughtTolerance: 'Moderate',
    heatTolerance: 'Low',
    growingDurationDays: 135,
    idealSoils: ['Loamy', 'Clay', 'Silty'],
    compatibleAfter: ['soybean', 'lentil', 'chickpea', 'maize', 'cover_crop'],
    incompatibleAfter: ['wheat'], // continuous cereals increase root-rot and take-all disease
    climateRiskScore: 35,
    typicalYieldTonPerHectare: 3.6,
    economicValue: 'Medium',
    carbonSequestration: 'Medium',
    description: 'Cool-season cereal offering reliable yields under moderate irrigation and excellent weed suppression.',
    icon: '🌾',
  },
  maize: {
    id: 'maize',
    name: 'Maize (Corn)',
    localNames: { bn: 'ভুট্টা (Maize)', en: 'Maize' },
    category: 'Cereal',
    waterDemand: 'High',
    waterDemandMmPerSeason: 650,
    soilImpact: 'Depleting',
    soilHealthDelta: -5,
    nitrogenFixing: false,
    droughtTolerance: 'Moderate',
    heatTolerance: 'High',
    growingDurationDays: 110,
    idealSoils: ['Loamy', 'Silty', 'Mixed'],
    compatibleAfter: ['soybean', 'chickpea', 'lentil', 'cover_crop'],
    incompatibleAfter: ['maize'], // corn rootworm buildup
    climateRiskScore: 48,
    typicalYieldTonPerHectare: 7.2,
    economicValue: 'High',
    carbonSequestration: 'Medium',
    description: 'Heavy feeder demanding high nitrogen; pairs symbiotically when succeeding nitrogen-fixing legumes.',
    icon: '🌽',
  },
  soybean: {
    id: 'soybean',
    name: 'Soybean',
    localNames: { bn: 'সয়াবিন (Soybean)', en: 'Soybean' },
    category: 'Legume',
    waterDemand: 'Medium',
    waterDemandMmPerSeason: 450,
    soilImpact: 'Regenerative',
    soilHealthDelta: 8,
    nitrogenFixing: true,
    droughtTolerance: 'Moderate',
    heatTolerance: 'Moderate',
    growingDurationDays: 105,
    idealSoils: ['Loamy', 'Clay', 'Mixed'],
    compatibleAfter: ['rice', 'wheat', 'maize', 'mustard'],
    incompatibleAfter: ['soybean'], // sudden death syndrome risks
    climateRiskScore: 30,
    typicalYieldTonPerHectare: 2.8,
    economicValue: 'High',
    carbonSequestration: 'High',
    description: 'Primary nitrogen-fixing legume that captures atmospheric nitrogen, replenishing subsoil nutrients for subsequent cereals.',
    icon: '🫘',
  },
  lentil: {
    id: 'lentil',
    name: 'Red / Brown Lentil',
    localNames: { bn: 'মসুর ডাল (Lentil)', en: 'Lentil' },
    category: 'Legume',
    waterDemand: 'Low',
    waterDemandMmPerSeason: 300,
    soilImpact: 'Regenerative',
    soilHealthDelta: 7,
    nitrogenFixing: true,
    droughtTolerance: 'High',
    heatTolerance: 'Moderate',
    growingDurationDays: 95,
    idealSoils: ['Loamy', 'Sandy', 'Mixed'],
    compatibleAfter: ['rice', 'wheat', 'maize', 'potato'],
    incompatibleAfter: ['lentil', 'chickpea'],
    climateRiskScore: 22,
    typicalYieldTonPerHectare: 1.6,
    economicValue: 'Medium',
    carbonSequestration: 'Medium',
    description: 'Ultra water-efficient cool-season pulse. Fixes up to 45 kg N/ha and breaks cereal disease cycles.',
    icon: '🫘',
  },
  chickpea: {
    id: 'chickpea',
    name: 'Chickpea (Garbanzo)',
    localNames: { bn: 'ছোলা (Chickpea)', en: 'Chickpea' },
    category: 'Legume',
    waterDemand: 'Low',
    waterDemandMmPerSeason: 280,
    soilImpact: 'Regenerative',
    soilHealthDelta: 9,
    nitrogenFixing: true,
    droughtTolerance: 'High',
    heatTolerance: 'High',
    growingDurationDays: 100,
    idealSoils: ['Loamy', 'Sandy', 'Silty'],
    compatibleAfter: ['wheat', 'rice', 'maize', 'mustard'],
    incompatibleAfter: ['chickpea', 'lentil'], // Ascochyta blight spore accumulation
    climateRiskScore: 20,
    typicalYieldTonPerHectare: 2.1,
    economicValue: 'High',
    carbonSequestration: 'High',
    description: 'Deep-taproot drought champion. Accesses deep soil moisture bands and deposits active organic matter.',
    icon: '🧆',
  },
  potato: {
    id: 'potato',
    name: 'Potato',
    localNames: { bn: 'আলু (Potato)', en: 'Potato' },
    category: 'Vegetable',
    waterDemand: 'Medium',
    waterDemandMmPerSeason: 500,
    soilImpact: 'Neutral',
    soilHealthDelta: -2,
    nitrogenFixing: false,
    droughtTolerance: 'Low',
    heatTolerance: 'Low',
    growingDurationDays: 90,
    idealSoils: ['Sandy', 'Loamy', 'Mixed'],
    compatibleAfter: ['wheat', 'maize', 'cover_crop', 'soybean'],
    incompatibleAfter: ['potato', 'tomato'], // Solanaceae early & late blight buildup
    climateRiskScore: 52,
    typicalYieldTonPerHectare: 24.0,
    economicValue: 'High',
    carbonSequestration: 'Low',
    description: 'High cash value tuber needing well-drained friable soils. Requires rotation away from nightshades.',
    icon: '🥔',
  },
  tomato: {
    id: 'tomato',
    name: 'Field Tomato',
    localNames: { bn: 'টমেটো (Tomato)', en: 'Tomato' },
    category: 'Vegetable',
    waterDemand: 'Medium',
    waterDemandMmPerSeason: 520,
    soilImpact: 'Neutral',
    soilHealthDelta: -3,
    nitrogenFixing: false,
    droughtTolerance: 'Low',
    heatTolerance: 'Moderate',
    growingDurationDays: 85,
    idealSoils: ['Loamy', 'Silty', 'Mixed'],
    compatibleAfter: ['soybean', 'wheat', 'mustard', 'cover_crop'],
    incompatibleAfter: ['tomato', 'potato'], // Verticillium/Fusarium wilt
    climateRiskScore: 56,
    typicalYieldTonPerHectare: 35.0,
    economicValue: 'High',
    carbonSequestration: 'Low',
    description: 'Intensive horticultural crop with high economic return. Highly vulnerable to continuous planting diseases.',
    icon: '🍅',
  },
  mustard: {
    id: 'mustard',
    name: 'Mustard / Brassica',
    localNames: { bn: 'সরিষা (Mustard)', en: 'Mustard' },
    category: 'Oilseed',
    waterDemand: 'Low',
    waterDemandMmPerSeason: 320,
    soilImpact: 'Regenerative',
    soilHealthDelta: 5,
    nitrogenFixing: false,
    droughtTolerance: 'High',
    heatTolerance: 'Moderate',
    growingDurationDays: 90,
    idealSoils: ['Loamy', 'Sandy', 'Clay', 'Mixed'],
    compatibleAfter: ['rice', 'wheat', 'maize', 'potato'],
    incompatibleAfter: ['mustard'], // clubroot accumulation
    climateRiskScore: 25,
    typicalYieldTonPerHectare: 1.7,
    economicValue: 'Medium',
    carbonSequestration: 'Medium',
    description: 'Bio-fumigant oilseed crop releasing glucosinolates that naturally suppress soil-borne fungal pathogens and nematodes.',
    icon: '🌼',
  },
  cover_crop: {
    id: 'cover_crop',
    name: 'Multi-Species Cover Crop',
    localNames: { bn: 'সবুজ সার / কভার ক্রপ', en: 'Cover Crop' },
    category: 'Cover Crop',
    waterDemand: 'Low',
    waterDemandMmPerSeason: 220,
    soilImpact: 'Regenerative',
    soilHealthDelta: 14,
    nitrogenFixing: true,
    droughtTolerance: 'High',
    heatTolerance: 'High',
    growingDurationDays: 70,
    idealSoils: ['Loamy', 'Sandy', 'Clay', 'Silty', 'Mixed', 'Unknown'],
    compatibleAfter: ['rice', 'wheat', 'maize', 'potato', 'tomato', 'soybean'],
    incompatibleAfter: [],
    climateRiskScore: 12,
    typicalYieldTonPerHectare: 0,
    economicValue: 'Low', // indirect economic return through soil restoration
    carbonSequestration: 'High',
    description: 'Cocktail of hairy vetch, clover, and annual ryegrass designed to maximize mycorrhizal fungal inoculation, prevent erosion, and fix organic nitrogen.',
    icon: '🌱',
  }
};

export const CROP_LIST: Crop[] = Object.values(CROPS);

export function getCropById(id: string): Crop {
  return CROPS[id] || CROPS.rice;
}
